version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node8
      - node10
      - node11
jobs:
  node8:
    working_directory: ~/mongoose-profiler
    docker:
      - image: node:8.15.1
    steps:
      - checkout
      - run: npm install
      - run: npm test

  node10:
    working_directory: ~/mongoose-profiler
    docker:
      - image: node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test

  node11:
    working_directory: ~/mongoose-profiler
    docker:
      - image: node:11.6.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
